spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    url: jdbc:postgresql://localhost:5432/htms
    password: '123456'
    hikari:
      data-source-properties:
        useUnicode: "true"
        characterEncoding: "UTF-8"
  jpa:
    properties:
      #      javax:
      #        persistence:
      #          schema-generation:
      #            create-source: metadata
      #            scripts:
      #              action: update
      #              create-target: update.sql
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: learning.fpt.edu@gmail.com
    password: diemoznaoiphyzwb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: '8080'
  servlet:
    context-path: /htms
account:
  password:
    length: 10