spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    url: jdbc:postgresql://localhost:5432/htms
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      #disable this to run flyway. If need to change anything to database, please create new flyway script to run
      ddl-auto: none
    show-sql: true
server:
  port: '8080'
  servlet:
    context-path: /htms