spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    url: jdbc:postgresql://localhost:5432/htms
    password: '123456'
  jpa:
    properties:
      #      javax:
      #        persistence:
      #          schema-generation:
      #            create-source: metadata
      #            scripts:
      #              action: update
      #              create-target: update.sql
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false

server:
  port: '8080'
  servlet:
    context-path: /htms